version: '3.8'
# docker-compose -f docker-compose-app-v1.0.yml up -d
services:
  # 部署前端项目
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - '8088:8088'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    privileged: true
  # ai-rag-knowledge
  ai-rag-app:
    image: zclau/ai-rag-app:1.0
    container_name: ai-rag-app
    restart: on-failure
    ports:
      - "8090:8090"
    environment:
      - TZ=PRC
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://127.0.0.1:15432/ai-rag-knowledge
      - SPRING_AI_OPENAI_BASE_URL=https://api.xxx.cn
      - SPRING_AI_OPENAI_API_KEY=pxfn*******************************************
      - SPRING_AI_OPENAI_EMBEDDING_MODEL=BAAI/bge-m3
      - SPRING_AI_OPENAI_EMBEDDING_DIMENSIONS=1024
      - SPRING_AI_VECTORSTORE_PGVECTOR_DIMENSIONS=1024
      - REDIS_SDK_CONFIG_HOST=127.0.0.1
      - REDIS_SDK_CONFIG_PORT=6379
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
